apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{service}}
  namespace: {{namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: {{service}}
  template:
    metadata:
      labels:
        k8s-app: {{service}}
        version: v1
    spec:
      containers:
      - name: {{service}}
        image: {{image}}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"
        ports:
        - containerPort: 8001
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{profiles}}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: dbconf
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: dbconf
              key: password
        - name: ENDPOINT
          valueFrom:
            secretKeyRef:
              name: dbconf
              key: endpoint
      imagePullSecrets:
        - name: ecr-secret
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{namespace}}
  name: {{service}}
spec:
  selector:
    k8s-app: {{service}}
  ports:
  - port: 8001
    name: http
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{service}}
  namespace: {{namespace}}
spec:
  rules:
  - host: {{service}}.{{team}}.{{profiles}}.twuc.school.thoughtworks.cn
    http:
      paths:
      - path: /
        backend:
          serviceName: {{service}}
          servicePort: 8001
